# Generated by Django 5.1.5 on 2026-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_uploads_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploads',
            name='conclusion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='judge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='abstract',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='formatting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='research_methodology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='results',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
