# Generated by Django 5.1.5 on 2026-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
