# Generated by Django 5.1.5 on 2026-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_uploads_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
