# Generated by Django 5.1.5 on 2026-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_uploads_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluator',
            old_name='judge',
            new_name='evaluator',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('dean', 'Dean'), ('evaluator', 'evaluator')], max_length=10),
        ),
    ]
