# Generated by Django 5.1.5 on 2026-03-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_judge_evaluator_evaluator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='judge_count',
            new_name='evaluator_count',
        ),
    ]
