# Generated by Django 6.0.1 on 2026-03-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_judge_count_uploads_evaluator_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='evaluator_count',
        ),
        migrations.AddField(
            model_name='evaluator',
            name='papers',
            field=models.ManyToManyField(related_name='evaluations', to='core.uploads'),
        ),
    ]
