# Generated by Django 6.0.1 on 2026-03-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_evaluator_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
