# Generated by Django 6.0.1 on 2026-03-14 12:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_uploads_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
